# docker-compose.yml

services:
    zookeeper:
        image: bitnami/zookeeper:latest
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        ports:
            - "2181:2181"

    kafka:
        image: bitnami/kafka:latest
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092

    redis:
        image: redis:latest
        ports:
            - "6379:6379"

    python:
        build:
            context: ./python
            dockerfile: Dockerfile
        depends_on:
            - kafka
            - redis
        volumes:
            - ./python:/app
            - ./db:/db
        env_file:
            - .env
